/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CategoryModal: typeof import('./src/components/CategoryModal.vue')['default']
    CategorySidebar: typeof import('./src/components/CategorySidebar.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NDataTable: typeof import('naive-ui')['NDataTable']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NInput: typeof import('naive-ui')['NInput']
    NInputNumber: typeof import('naive-ui')['NInputNumber']
    NList: typeof import('naive-ui')['NList']
    NListItem: typeof import('naive-ui')['NListItem']
    NModal: typeof import('naive-ui')['NModal']
    NSelect: typeof import('naive-ui')['NSelect']
    NSpace: typeof import('naive-ui')['NSpace']
    NText: typeof import('naive-ui')['NText']
    PriceFormModal: typeof import('./src/components/PriceFormModal.vue')['default']
    PriceTable: typeof import('./src/components/PriceTable.vue')['default']
  }
}
